import type { TodoItem } from "@/lib/types";
import { addDaysKeepTime, defaultDue, nowLocal } from "@/lib/dates";

export function seedItems(): TodoItem[] {
  const dueSoon = defaultDue();
  const later = addDaysKeepTime(dueSoon, 1);
  const stamp = nowLocal();
  return [
    {
      id: "seed-dongguan-quote",
      customer: "东莞晶冠",
      type: "报价",
      content: "STM32F103C8T6 × 5K，今天下班前要价",
      amount: null,
      status: "待处理",
      dueAt: dueSoon,
      dueDefault: true,
      createdAt: stamp,
      doneAt: null,
      carryCount: 0,
      dueOrig: dueSoon,
    },
    {
      id: "seed-weisheng-order",
      customer: "深圳威盛",
      type: "下单",
      content: "ESP32-WROOM-32E 10K，交期已确认",
      amount: 18500,
      status: "处理中",
      dueAt: dueSoon,
      dueDefault: true,
      createdAt: stamp,
      doneAt: null,
      carryCount: 0,
      dueOrig: dueSoon,
    },
    {
      id: "seed-xunke-ship",
      customer: "广州迅科",
      type: "发货",
      content: "0402 电容那批走顺丰，收货人王工",
      amount: 3200,
      status: "待处理",
      dueAt: later,
      dueDefault: false,
      createdAt: stamp,
      doneAt: null,
      carryCount: 1,
      dueOrig: dueSoon,
    },
    {
      id: "seed-xinyuan-bill",
      customer: "杭州芯原",
      type: "对账",
      content: "7 月账单核对，差 2 个型号",
      amount: 8600,
      status: "待处理",
      dueAt: dueSoon,
      dueDefault: true,
      createdAt: stamp,
      doneAt: null,
      carryCount: 0,
      dueOrig: dueSoon,
    },
    {
      id: "seed-dongguan-invoice",
      customer: "东莞晶冠",
      type: "发票",
      content: "开专票 13%，公司名东莞晶冠电子有限公司",
      amount: 12000,
      status: "已完成",
      dueAt: dueSoon,
      dueDefault: true,
      createdAt: stamp,
      doneAt: stamp,
      carryCount: 0,
      dueOrig: dueSoon,
    },
  ];
}
